### ISSUE TITLE
Plugin LIGHTBOX

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#164]
¿Existe algún plugin tipo lightbox para que las imágenes con enlace a sí mismas se abran sin necesidad de una pestaña nueva?
Es siempre muy incómodo pinchar para agrandar una imagen y que se abra en una pestaña nueva.
En Wordpress lo llaman lightbox. En páginas como http://staging.martadero.org/pagina/ayer-y-hoy sería realmente bueno.

**Comment by hdwilber** [comment]
I have embedded some HTML and JS code to take out onclick attribute from <A> tag containing an <img> tag. Then, take the href attribute in order to load the image in the same page inside a popup dialog(#image-viewer).
Sorry, this code is not a Full featured LightBox Plugin, only the main behaviour has been coded.

**Comment by jgenso** [comment]
its fine
