### ISSUE TITLE
Espacio costos sala

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/federica#174]
He intentado ver si con CSS se podía dar espacio a los items de pago de sala por área pero ni modo... la única forma que encontré fue ponerle dos br.
Si encuentras otra forma @marcelorodcla  súper, no he modificado nada en los hmtl por si la cago.

![espacio_costos_sala](https://cloud.githubusercontent.com/assets/7635775/14147042/ec8a5476-f667-11e5-942e-8c4f6f2c96c9.jpg)

**Comment by hdwilber** [comment]
I have grouped those rows in another container with class "section-costs" , in order to set a vertical spanning between them by using stylesheets.
- In Development mode:  Now, the LESS stylesheets are compiled on client side. 
- In Production mode: the LESS stylesheets will be compiled on server side.
